Mipa\ImageBundle\Entity\Image:
  type: entity
  table: image
  id:
    id:
      type:integer
      generator: { strategy: AUTO }
  fields:
    title:
      type: string
      length: 225
    image:
      type: image