mipa_image_mipa_img:
    resource: "@MipaImageBundle/Resources/config/routing/images.yml"
    prefix:   /images

mipa_image_homepage:
    path:     /hello/{name}
    defaults: { _controller: MipaImageBundle:Default:index }

login:
    pattern:   /login
    defaults:  { _controller: MipaImageBundle:Default:login }
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout

mipa_image_rest:
    resource: "@MipaImageBundle/Resources/config/routing/rest.yml"
    prefix:   /api
